# Introduction to NumPy

**NumPy** is a library written for scientific computing and data analysis. It stands for numerical python.

The most basic object in NumPy is the ```array```, which is **homogenous** in nature. By homogenous, we mean that all the elements in a numpy array have to be of the **same data type**, which is commonly numeric (float or integer). 

### Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

In [2]:
! pip install numpy         # to insatall numpy in notebook

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
# Import the numpy library
# np is simply an alias, you may use any other alias, though np is quite standard
import numpy as np
print(np.__version__)    # check the version of the numpy library

1.22.4


In [3]:
numbers=[1,2,3]  # list of the numbers
arr=np.array(numbers)    # creates a numpy array
print('list:',numbers)
print(type(numbers))
print('-----------------------------------------')
print('numpy array:',arr)
print(type(arr))

list: [1, 2, 3]
<class 'list'>
-----------------------------------------
numpy array: [1 2 3]
<class 'numpy.ndarray'>


### Numpy vs Lists 

In [1]:
#Speed

import time
import numpy as np

# Create two large lists of numbers
list_a = list(range(10**6))
list_b = list(range(1, 10**6 + 1))

# Create two NumPy arrays from the lists
array_a = np.array(list_a)
array_b = np.array(list_b)

# Measure time taken to add large lists in Python
start_time = time.time()
result_list = [a + b for a, b in zip(list_a, list_b)]
end_time = time.time()
python_time = end_time - start_time

# Measure time taken to add large arrays in NumPy
start_time = time.time()
result_array = array_a + array_b
end_time = time.time()
numpy_time = end_time - start_time

# Print the results
print("Time taken for list addition in Python:", python_time*1000)
print("Time taken for array addition in NumPy:", numpy_time*1000)


Time taken for list addition in Python: 94.15817260742188
Time taken for array addition in NumPy: 1.008749008178711


Lists cannot operate over the entire data together. You need to run _map_ or _lambda_ functions to multiply each element with 2.5. 

In [7]:
list_1=[1,2,3]
def mul(x):
    return x*2.5
print(list(map(mul,list_1)))

[2.5, 5.0, 7.5]


In [8]:
list_2=list(map(lambda x: x*2.5,list_1))

In [9]:
print(list_2)

[2.5, 5.0, 7.5]


In [10]:
list_1*2         # if we multiply list with an integer it will perform repetition

[1, 2, 3, 1, 2, 3]

Let's try to perform the same using a NumPy array.

In [11]:
# Creating a 1-D array using a list
# np.array() takes in a list or a tuple as argument, and converts into an array

np_list = np.array(list_1)

In [12]:
np_list

array([1, 2, 3])

In [13]:
# Multiply each element with 2.5 

np_list*2.5

array([2.5, 5. , 7.5])

In [14]:
# Print the result using the print command. Compare the structure of list and array.
print(np_list,list_1)

[1 2 3] [1, 2, 3]


## Creating 1D numpy array using different data types

In [27]:
# Create a 1-D array using with the elements (1, abc, True)

np.array([1,"abc",True])

array(['1', 'abc', 'True'], dtype='<U21')

In [15]:
# Create a 1-D array using with the elements (1, abc, True)

a=np.array([1,"abc",True])
print(a)

['1' 'abc' 'True']


All the elements in a numpy array have the same data type. You can check the data type of an array using the `.dtype`

The type of the data can be described by type attribute as `.dtype.type`

In [16]:
print('type(a): ',type(a))                  # check the data type of the array
print('a.dtype: ',a.dtype)                  # check the data type of the elements of the array
print('a.dtype.type: ',a.dtype.type)        # check the data type of the elements of the array


type(a):  <class 'numpy.ndarray'>
a.dtype:  <U21
a.dtype.type:  <class 'numpy.str_'>


In [17]:
x=np.array(['Apple','Banana','Orange'])
print(type(x))
print(x.dtype)
print(x.dtype.type)

<class 'numpy.ndarray'>
<U6
<class 'numpy.str_'>


In [18]:
list_1=[5,1,5,9]

In [19]:
list_1=np.array(list_1)
print(list_1.dtype)
print(list_1.dtype.type)

int64
<class 'numpy.int64'>


In [29]:
list_2=[5,1.5,5,9]
np_list_2=np.array(list_2)
print(np_list_2.dtype.type)

<class 'numpy.str_'>


In [21]:
list_float=[1.5,2.5,3.5,4,7]
arr=np.array(list_float)
print(arr.dtype)
print(arr.dtype.type)

float64
<class 'numpy.float64'>


In [22]:
list_float=[1.5,2.5,3.5,4,7]
arr=np.array(list_float)
print(arr.dtype)
print(arr.dtype.type)

float64
<class 'numpy.float64'>


In [23]:
print(type(8.3))

<class 'float'>


In [24]:
list_float=[1,2,3,4,7,True]
arr=np.array(list_float)
print(arr.dtype)
print(arr.dtype.type)

int64
<class 'numpy.int64'>


### Checking shape, dimensions, size

Numpy arrays can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the `.shape `property of an array.


You can get the number of dimensions, and size (number of all elements) of the NumPy array with ndim and size attributes of numpy.ndarray. The built-in function len() returns the size of the first dimension.

- Number of dimensions of the NumPy array: `.ndim`

- Size of the NumPy array: `.size`

- Size of the first dimension of the NumPy array: `len()`


In [25]:
list_1=[5,1,5,9]
arr=np.array(list_1)
print('arr.shape',arr.shape)       # check the shape of the numpy array
print('arr.ndim: ',arr.ndim)       # check the dimensions of the numpy array 
print('arr.size: ',arr.size)       # check the size of the numpy array
print('len(arr): ',len(arr))

arr.shape (4,)
arr.ndim:  1
arr.size:  4
len(arr):  4


In [26]:
# create a numpy array of the single element
list_2=2
list_2=np.array(list_2)
print('list_2.ndim: ',list_2.ndim)
print('list_2.shape: ',list_2.shape)
print('type(list_2): ',type(list_2))
print('list_2.dtype: ',list_2.dtype)

list_2.ndim:  0
list_2.shape:  ()
type(list_2):  <class 'numpy.ndarray'>
list_2.dtype:  int64


## Broadcasting

![](https://i.imgur.com/BRJejKJ.jpg)


The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.


for further reading refer: https://numpy.org/doc/stable/user/basics.broadcasting.html


NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape, as in the following example:

In [31]:
a = np.array([1.0, 2.0, 3.0])
b=2
c=a**b

print(c)

[1. 4. 9.]


## Creating 2D and 3D array
![](https://i.imgur.com/pMjzthM.png)

Numpy is used to create multi dimensional arrays. For 2D array it is having sahpe along two axes axis 0 for rows and axis 1 for columns if we consider it as mxn matrix. Elements in 2D arrays are similar to list of lists. for example,[[1,2,3],[4,5,6]]. The given array will have shape (2,3). 

For 3D array it will have shape along axis 2 as depth, axis 0 as height and axis 1 as length of the cube. for example [[[1,2,3],[4,5,6],[7,8,9]]]. In this example the shape of the array is (1,3,3)

In [ ]:
# Creating a 2D array
list_1=[[1,2,3],[4,5,6]]
arr1=np.array(list_1)
print('arr1: \n',arr1)
print('arr1.shape: ',arr1.shape)
print('arr1.ndim: ',arr1.ndim)
print('arr1.size: ',arr1.size)

arr1: 
 [[1 2 3]
 [4 5 6]]
arr1.shape:  (2, 3)
arr1.ndim:  2
arr1.size:  6


In [ ]:
arr1[0]

array([1, 2, 3])

In [ ]:
# creating a 3D array
list_2=[[[1,2,3],[4,5,6]]]
arr2=np.array(list_2)
print('arr12 \n',arr2)
print('arr2.shape: ',arr2.shape)
print('arr2.ndim: ',arr2.ndim)
print('arr2.size: ',arr2.size)

arr12 
 [[[1 2 3]
  [4 5 6]]]
arr2.shape:  (1, 2, 3)
arr2.ndim:  3
arr2.size:  6


In [ ]:
arr2[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
list_x=np.array([[[1],[2],[3]],[[4],[5],[6]]])
list_x.shape

(2, 3, 1)

In [ ]:
list_x=np.array([[[1],[2],[3]],[[4],[5],[6]],[[1],[2],[3]],[[4],[5],[6]]])
list_x.shape

(4, 3, 1)

In [32]:
arr=np.array([[[1,2,3],[6,8,9]],[[9,11,13],[101,1,13]]])
print('shape of arr: ',arr.shape)
print('number of dimensions: ',arr.ndim)
print('Number of elements in the array: ',arr.size)

shape of arr:  (2, 2, 3)
number of dimensions:  3
Number of elements in the array:  12


In [33]:
arr[1]

array([[  9,  11,  13],
       [101,   1,  13]])

In [34]:
arr[1][1]

array([101,   1,  13])

In [35]:
arr[1][1][1]

1

In [41]:
arr[1,1][::2]

array([101,  13])

## Array slicing

![](https://i.imgur.com/tcgquis.png)

To slice a one dimensional array, I provide a start and an end number separated by a semicolon (:). The range then starts at the start number and one before the end number.




### Multidimensional Arrays

A multidimensional array is an array of arrays. For example, a two dimensional array would be an array with each element as one-dimensional array. 

1-D array : [1, 2, 3, 4, 5]

2-D array : [ [1, 2, 3, 4, 5], [6, 7, 8, 9, 10] ]

Similary for a n-dimensional array

In NumPy, dimension is called axis. In Numpy terminology, for 2-D arrays:
*  axis = 0 refers to the rows
*  axis = 1 refers to the columns

![image.png](attachment:image.png)

**Multidimensional arrays** are indexed using as many indices as the number of dimensions or axes. For instance, to index a 2-D array, you need two indices - ```array[x, y]```.  Each axes has an index starting at 0. 

In [42]:
# import numpy library

import numpy as np
# player information is provided in the lists - players, skills
# players: list of tuples where 1st element is height in inches and the 2nd element is weight in lbs
# skills: the skill of the player in the sport cricket

players = [(74, 180), (74, 215), (72, 210), (72, 210), (73, 188), (69, 176), (69, 209), (71, 200), (76, 231), (71, 180), (73, 188), (73, 180), (74, 185), (74, 160), (69, 180), (70, 185), (73, 189), (75, 185), (78, 219), (79, 230), (76, 205), (74, 230), (76, 195), (72, 180), (71, 192), (75, 225), (77, 203), (74, 195), (73, 182), (74, 188), (78, 200), (73, 180), (75, 200), (73, 200), (75, 245), (75, 240), (74, 215), (69, 185), (71, 175), (74, 199), (73, 200), (73, 215), (76, 200), (74, 205), (74, 206), (70, 186), (72, 188), (77, 220), (74, 210), (70, 195), (73, 200), (75, 200), (76, 212), (76, 224), (78, 210), (74, 205), (74, 220), (76, 195), (77, 200), (81, 260), (78, 228), (75, 270), (77, 200), (75, 210), (76, 190), (74, 220), (72, 180), (72, 205), (75, 210), (73, 220), (73, 211), (73, 200), (70, 180), (70, 190), (70, 170), (76, 230), (68, 155), (71, 185), (72, 185), (75, 200), (75, 225), (75, 225), (75, 220), (68, 160), (74, 205), (78, 235), (71, 250), (73, 210), (76, 190), (74, 160), (74, 200), (79, 205), (75, 222), (73, 195), (76, 205), (74, 220), (74, 220), (73, 170), (72, 185), (74, 195), (73, 220), (74, 230), (72, 180), (73, 220), (69, 180), (72, 180), (73, 170), (75, 210), (75, 215), (73, 200), (72, 213), (72, 180), (76, 192), (74, 235), (72, 185), (77, 235), (74, 210), (77, 222), (75, 210), (76, 230), (80, 220), (74, 180), (74, 190), (75, 200), (78, 210), (73, 194), (73, 180), (74, 190), (75, 240), (76, 200), (71, 198), (73, 200), (74, 195), (76, 210), (76, 220), (74, 190), (73, 210), (74, 225), (70, 180), (72, 185), (73, 170), (73, 185), (73, 185), (73, 180), (71, 178), (74, 175), (74, 200), (72, 204), (74, 211), (71, 190), (74, 210), (73, 190), (75, 190), (75, 185), (79, 290), (73, 175), (75, 185), (76, 200), (74, 220), (76, 170), (78, 220), (74, 190), (76, 220), (72, 205), (74, 200), (76, 250), (74, 225), (75, 215), (78, 210), (75, 215), (72, 195), (74, 200), (72, 194), (74, 220), (70, 180), (71, 180), (70, 170), (75, 195), (71, 180), (71, 170), (73, 206), (72, 205), (71, 200), (73, 225), (72, 201), (75, 225), (74, 233), (74, 180), (75, 225), (73, 180), (77, 220), (73, 180), (76, 237), (75, 215), (74, 190), (76, 235), (75, 190), (73, 180), (71, 165), (76, 195), (75, 200), (72, 190), (71, 190), (77, 185), (73, 185), (74, 205), (71, 190), (72, 205), (74, 206), (75, 220), (73, 208), (72, 170), (75, 195), (75, 210), (74, 190), (72, 211), (74, 230), (71, 170), (70, 185), (74, 185), (77, 241), (77, 225), (75, 210), (75, 175), (78, 230), (75, 200), (76, 215), (73, 198), (75, 226), (75, 278), (79, 215), (77, 230), (76, 240), (71, 184), (75, 219), (74, 170), (69, 218), (71, 190), (76, 225), (72, 220), (72, 176), (70, 190), (72, 197), (73, 204), (71, 167), (72, 180), (71, 195), (73, 220), (72, 215), (73, 185), (74, 190), (74, 205), (72, 205), (75, 200), (74, 210), (74, 215), (77, 200), (75, 205), (73, 211), (72, 190), (71, 208), (74, 200), (77, 210), (75, 232), (75, 230), (75, 210), (78, 220), (78, 210), (74, 202), (76, 212), (78, 225), (76, 170), (70, 190), (72, 200), (80, 237), (74, 220), (74, 170), (71, 193), (70, 190), (72, 150), (71, 220), (74, 200), (71, 190), (72, 185), (71, 185), (74, 200), (69, 172), (76, 220), (75, 225), (75, 190), (76, 195), (73, 219), (76, 190), (73, 197), (77, 200), (73, 195), (72, 210), (72, 177), (77, 220), (77, 235), (71, 180), (74, 195), (74, 195), (73, 190), (78, 230), (75, 190), (73, 200), (70, 190), (74, 190), (72, 200), (73, 200), (73, 184), (75, 200), (75, 180), (74, 219), (76, 187), (73, 200), (74, 220), (75, 205), (75, 190), (72, 170), (73, 160), (73, 215), (72, 175), (74, 205), (78, 200), (76, 214), (73, 200), (74, 190), (75, 180), (70, 205), (75, 220), (71, 190), (72, 215), (78, 235), (75, 191), (73, 200), (73, 181), (71, 200), (75, 210), (77, 240), (72, 185), (69, 165), (73, 190), (74, 185), (72, 175), (70, 155), (75, 210), (70, 170), (72, 175), (72, 220), (74, 210), (73, 205), (74, 200), (76, 205), (75, 195), (80, 240), (72, 150), (75, 200), (73, 215), (74, 202), (74, 200), (73, 190), (75, 205), (75, 190), (71, 160), (73, 215), (75, 185), (74, 200), (74, 190), (72, 210), (74, 185), (74, 220), (74, 190), (73, 202), (76, 205), (75, 220), (72, 175), (73, 160), (73, 190), (73, 200), (72, 229), (72, 206), (72, 220), (72, 180), (71, 195), (75, 175), (75, 188), (74, 230), (73, 190), (75, 200), (79, 190), (74, 219), (76, 235), (73, 180), (74, 180), (74, 180), (72, 200), (74, 234), (74, 185), (75, 220), (78, 223), (74, 200), (74, 210), (74, 200), (77, 210), (70, 190), (73, 177), (74, 227), (73, 180), (71, 195), (75, 199), (71, 175), (72, 185), (77, 240), (74, 210), (70, 180), (77, 194), (73, 225), (72, 180), (76, 205), (71, 193), (76, 230), (78, 230), (75, 220), (73, 200), (78, 249), (74, 190), (79, 208), (75, 245), (76, 250), (72, 160), (75, 192), (75, 220), (70, 170), (72, 197), (70, 155), (74, 190), (71, 200), (76, 220), (73, 210), (76, 228), (71, 190), (69, 160), (72, 184), (72, 180), (69, 180), (73, 200), (69, 176), (73, 160), (74, 222), (74, 211), (72, 195), (71, 200), (72, 175), (72, 206), (76, 240), (76, 185), (76, 260), (74, 185), (76, 221), (75, 205), (71, 200), (72, 170), (71, 201), (73, 205), (75, 185), (76, 205), (75, 245), (71, 220), (75, 210), (74, 220), (72, 185), (73, 175), (73, 170), (73, 180), (73, 200), (76, 210), (72, 175), (76, 220), (73, 206), (73, 180), (73, 210), (75, 195), (75, 200), (77, 200), (73, 164), (72, 180), (75, 220), (70, 195), (74, 205), (72, 170), (80, 240), (71, 210), (71, 195), (74, 200), (74, 205), (73, 192), (75, 190), (76, 170), (73, 240), (77, 200), (72, 205), (73, 175), (77, 250), (76, 220), (71, 224), (75, 210), (73, 195), (74, 180), (77, 245), (71, 175), (72, 180), (73, 215), (69, 175), (73, 180), (70, 195), (74, 230), (76, 230), (73, 205), (73, 215), (75, 195), (73, 180), (79, 205), (74, 180), (73, 190), (74, 180), (77, 190), (75, 190), (74, 220), (73, 210), (77, 255), (73, 190), (77, 230), (74, 200), (74, 205), (73, 210), (77, 225), (74, 215), (77, 220), (75, 205), (77, 200), (75, 220), (71, 197), (74, 225), (70, 187), (79, 245), (72, 185), (72, 185), (70, 175), (74, 200), (74, 180), (72, 188), (73, 225), (72, 200), (74, 210), (74, 245), (76, 213), (82, 231), (74, 165), (74, 228), (70, 210), (73, 250), (73, 191), (74, 190), (77, 200), (72, 215), (76, 254), (73, 232), (73, 180), (72, 215), (74, 220), (74, 180), (71, 200), (72, 170), (75, 195), (74, 210), (74, 200), (77, 220), (70, 165), (71, 180), (73, 200), (76, 200), (71, 170), (75, 224), (74, 220), (72, 180), (76, 198), (79, 240), (76, 239), (73, 185), (76, 210), (78, 220), (75, 200), (76, 195), (72, 220), (72, 230), (73, 170), (73, 220), (75, 230), (71, 165), (76, 205), (70, 192), (75, 210), (74, 205), (75, 200), (73, 210), (71, 185), (71, 195), (72, 202), (73, 205), (73, 195), (72, 180), (69, 200), (73, 185), (78, 240), (71, 185), (73, 220), (75, 205), (76, 205), (70, 180), (74, 201), (77, 190), (75, 208), (79, 240), (72, 180), (77, 230), (73, 195), (75, 215), (75, 190), (75, 195), (73, 215), (73, 215), (76, 220), (77, 220), (75, 230), (70, 195), (71, 190), (71, 195), (75, 209), (74, 204), (69, 170), (70, 185), (75, 205), (72, 175), (75, 210), (73, 190), (72, 180), (72, 180), (72, 160), (76, 235), (75, 200), (74, 210), (69, 180), (73, 190), (72, 197), (72, 203), (75, 205), (77, 170), (76, 200), (80, 250), (77, 200), (76, 220), (79, 200), (71, 190), (75, 170), (73, 190), (76, 220), (77, 215), (73, 206), (76, 215), (70, 185), (75, 235), (73, 188), (75, 230), (70, 195), (69, 168), (71, 190), (72, 160), (72, 200), (73, 200), (70, 189), (70, 180), (73, 190), (76, 200), (75, 220), (72, 187), (73, 240), (79, 190), (71, 180), (72, 185), (74, 210), (74, 220), (74, 219), (72, 190), (76, 193), (76, 175), (72, 180), (72, 215), (71, 210), (72, 200), (72, 190), (70, 185), (77, 220), (74, 170), (72, 195), (76, 205), (71, 195), (76, 210), (71, 190), (73, 190), (70, 180), (73, 220), (73, 190), (72, 186), (71, 185), (71, 190), (71, 180), (72, 190), (72, 170), (74, 210), (74, 240), (74, 220), (71, 180), (72, 210), (75, 210), (72, 195), (71, 160), (72, 180), (72, 205), (72, 200), (72, 185), (74, 245), (74, 190), (77, 210), (75, 200), (73, 200), (75, 222), (73, 215), (76, 240), (72, 170), (77, 220), (75, 156), (72, 190), (71, 202), (71, 221), (75, 200), (72, 190), (73, 210), (73, 190), (71, 200), (70, 165), (75, 190), (71, 185), (76, 230), (73, 208), (68, 209), (71, 175), (72, 180), (74, 200), (77, 205), (72, 200), (76, 250), (78, 210), (81, 230), (72, 244), (73, 202), (76, 240), (72, 200), (72, 215), (74, 177), (76, 210), (73, 170), (76, 215), (75, 217), (70, 198), (71, 200), (74, 220), (72, 170), (73, 200), (76, 230), (76, 231), (73, 183), (71, 192), (68, 167), (71, 190), (71, 180), (74, 180), (77, 215), (69, 160), (72, 205), (76, 223), (75, 175), (76, 170), (75, 190), (76, 240), (72, 175), (74, 230), (76, 223), (74, 196), (72, 167), (75, 195), (78, 190), (77, 250), (70, 190), (72, 190), (79, 190), (74, 170), (71, 160), (68, 150), (77, 225), (75, 220), (71, 209), (72, 210), (70, 176), (72, 260), (72, 195), (73, 190), (72, 184), (74, 180), (72, 195), (72, 195), (75, 219), (72, 225), (73, 212), (74, 202), (72, 185), (78, 200), (75, 209), (72, 200), (74, 195), (75, 228), (75, 210), (76, 190), (74, 212), (74, 190), (73, 218), (74, 220), (71, 190), (74, 235), (75, 210), (76, 200), (74, 188), (76, 210), (76, 235), (73, 188), (75, 215), (75, 216), (74, 220), (68, 180), (72, 185), (75, 200), (71, 210), (70, 220), (72, 185), (73, 231), (72, 210), (75, 195), (74, 200), (70, 205), (76, 200), (71, 190), (82, 250), (72, 185), (73, 180), (74, 170), (71, 180), (75, 208), (77, 235), (72, 215), (74, 244), (72, 220), (73, 185), (78, 230), (77, 190), (73, 200), (73, 180), (73, 190), (73, 196), (73, 180), (76, 230), (75, 224), (70, 160), (73, 178), (72, 205), (73, 185), (75, 210), (74, 180), (73, 190), (73, 200), (76, 257), (73, 190), (75, 220), (70, 165), (77, 205), (72, 200), (77, 208), (74, 185), (75, 215), (75, 170), (75, 235), (75, 210), (72, 170), (74, 180), (71, 170), (76, 190), (71, 150), (75, 230), (76, 203), (83, 260), (75, 246), (74, 186), (76, 210), (72, 198), (72, 210), (75, 215), (75, 180), (72, 200), (77, 245), (73, 200), (72, 192), (70, 192), (74, 200), (72, 192), (74, 205), (72, 190), (71, 186), (70, 170), (71, 197), (76, 219), (74, 200), (76, 220), (74, 207), (74, 225), (74, 207), (75, 212), (75, 225), (71, 170), (71, 190), (74, 210), (77, 230), (71, 210), (74, 200), (75, 238), (77, 234), (76, 222), (74, 200), (76, 190), (72, 170), (71, 220), (72, 223), (75, 210), (73, 215), (68, 196), (72, 175), (69, 175), (73, 189), (73, 205), (75, 210), (70, 180), (70, 180), (74, 197), (75, 220), (74, 228), (74, 190), (73, 204), (74, 165), (75, 216), (77, 220), (73, 208), (74, 210), (76, 215), (74, 195), (75, 200), (73, 215), (76, 229), (78, 240), (75, 207), (73, 205), (77, 208), (74, 185), (72, 190), (74, 170), (72, 208), (71, 225), (73, 190), (75, 225), (73, 185), (67, 180), (67, 165), (76, 240), (74, 220), (73, 212), (70, 163), (75, 215), (70, 175), (72, 205), (77, 210), (79, 205), (78, 208), (74, 215), (75, 180), (75, 200), (78, 230), (76, 211), (75, 230), (69, 190), (75, 220), (72, 180), (75, 205), (73, 190), (74, 180), (75, 205), (75, 190), (73, 195)]
skills = np.array(['Keeper', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper', 'Keeper', 'Keeper', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper', 'Batsman', 'Keeper', 'Bowler', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Keeper', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Batsman', 'Bowler', 'Keeper', 'Keeper', 'Batsman', 'Bowler', 'Bowler', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Keeper', 'Bowler', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Bowler', 'Keeper', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Bowler', 'Keeper', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Bowler', 'Keeper', 'Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Bowler', 'Keeper', 'Bowler', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman'])


In [44]:
# Creating a 2-D array using the list of tuples
np_players = np.array(players)

# Checking the created array
print(np_players)

[[ 74 180]
 [ 74 215]
 [ 72 210]
 ...
 [ 75 205]
 [ 75 190]
 [ 73 195]]


In [45]:
# checking the type of created object
type(np_players)

numpy.ndarray

In [46]:
# printing the number of columns and rows in the array
np_players.shape

(1015, 2)

In [47]:
# printing the dimensions of the array
np_players.ndim

2

In [48]:
# printing the data type of the elements in the array
np_players.dtype

dtype('int64')

### Slicing a 2D array

In [49]:
# printing the entire second row of the 2-D array
np_players[1]

array([ 74, 215])

In [50]:
# printing the second column of the second row of the 2-D array
np_players[1][1]

215

In [55]:
import sys
np.set_printoptions(threshold=sys.maxsize)

In [56]:
# printing the first column (height of the players) with all the rows of the 2-D array 
np_players[:,0]

array([74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73,
       75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73,
       75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73,
       75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72,
       75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74,
       78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74,
       72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75,
       76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74,
       73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75,
       75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75,
       72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74,
       74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77,
       73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77,
       77, 75, 75, 78, 75

In [59]:
# printing only those rows where height of the player is more than 75 inches
gr_75=np_players[np_players[:,0]>75]

In [63]:
gr_75

array([[ 76, 231],
       [ 78, 219],
       [ 79, 230],
       [ 76, 205],
       [ 76, 195],
       [ 77, 203],
       [ 78, 200],
       [ 76, 200],
       [ 77, 220],
       [ 76, 212],
       [ 76, 224],
       [ 78, 210],
       [ 76, 195],
       [ 77, 200],
       [ 81, 260],
       [ 78, 228],
       [ 77, 200],
       [ 76, 190],
       [ 76, 230],
       [ 78, 235],
       [ 76, 190],
       [ 79, 205],
       [ 76, 205],
       [ 76, 192],
       [ 77, 235],
       [ 77, 222],
       [ 76, 230],
       [ 80, 220],
       [ 78, 210],
       [ 76, 200],
       [ 76, 210],
       [ 76, 220],
       [ 79, 290],
       [ 76, 200],
       [ 76, 170],
       [ 78, 220],
       [ 76, 220],
       [ 76, 250],
       [ 78, 210],
       [ 77, 220],
       [ 76, 237],
       [ 76, 235],
       [ 76, 195],
       [ 77, 185],
       [ 77, 241],
       [ 77, 225],
       [ 78, 230],
       [ 76, 215],
       [ 79, 215],
       [ 77, 230],
       [ 76, 240],
       [ 76, 225],
       [ 77,

In [61]:
# printing only those rows where height of the player is more than 75 inches print their weights
np_players[np_players[:,0]>75][:,1]

array([231, 219, 230, 205, 195, 203, 200, 200, 220, 212, 224, 210, 195,
       200, 260, 228, 200, 190, 230, 235, 190, 205, 205, 192, 235, 222,
       230, 220, 210, 200, 210, 220, 290, 200, 170, 220, 220, 250, 210,
       220, 237, 235, 195, 185, 241, 225, 230, 215, 215, 230, 240, 225,
       200, 210, 220, 210, 212, 225, 170, 237, 220, 195, 190, 200, 220,
       235, 230, 187, 200, 214, 235, 240, 205, 240, 205, 190, 235, 223,
       210, 240, 194, 205, 230, 230, 249, 208, 250, 220, 228, 240, 185,
       260, 221, 205, 210, 220, 200, 240, 170, 200, 250, 220, 245, 230,
       205, 190, 255, 230, 225, 220, 200, 245, 213, 231, 200, 254, 220,
       200, 198, 240, 239, 210, 220, 195, 205, 240, 205, 190, 240, 230,
       220, 220, 235, 170, 200, 250, 200, 220, 200, 220, 215, 215, 200,
       190, 193, 175, 220, 205, 210, 210, 240, 220, 230, 205, 250, 210,
       230, 240, 210, 215, 230, 231, 215, 223, 170, 240, 223, 190, 250,
       190, 225, 200, 190, 200, 210, 235, 200, 250, 235, 230, 19

### Slicing one array based on the other

In [74]:
# printing those rows where the skill of the player is 'Batsman'
Batsman=np_players[skills=="Batsman"]

In [75]:
Batsman[Batsman[:,0]>75]

array([[ 76, 231],
       [ 79, 230],
       [ 77, 203],
       [ 76, 195],
       [ 76, 190],
       [ 78, 235],
       [ 76, 205],
       [ 77, 235],
       [ 77, 222],
       [ 76, 230],
       [ 80, 220],
       [ 76, 210],
       [ 76, 237],
       [ 76, 235],
       [ 77, 225],
       [ 78, 230],
       [ 76, 225],
       [ 77, 210],
       [ 78, 220],
       [ 78, 210],
       [ 78, 225],
       [ 76, 195],
       [ 77, 220],
       [ 77, 235],
       [ 78, 230],
       [ 78, 200],
       [ 76, 214],
       [ 78, 235],
       [ 77, 240],
       [ 76, 205],
       [ 77, 240],
       [ 76, 230],
       [ 76, 205],
       [ 76, 210],
       [ 77, 200],
       [ 76, 220],
       [ 77, 245],
       [ 77, 190],
       [ 77, 255],
       [ 77, 230],
       [ 79, 245],
       [ 82, 231],
       [ 76, 254],
       [ 76, 239],
       [ 76, 210],
       [ 78, 220],
       [ 76, 195],
       [ 79, 240],
       [ 76, 235],
       [ 76, 200],
       [ 77, 215],
       [ 76, 193],
       [ 76,

# Manipulating Arrays

![](https://i.imgur.com/mg7tMCb.png)

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Reshaping
*  Stacking
*  Concatenating
*  Sorting
*  Padding
*  Splitting


### Reshaping

In [76]:
# Creating an array of first ten natural numbers
arr_4 = np.arange(10)

# Printing the created array
arr_4,arr_4.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), (10,))

In [77]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
arr_5 = arr_4.reshape(5,2)

In [78]:
# Checking the rows and columns in the created array
arr_5

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [79]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = np.arange(20,40).reshape(5,4)

# Checking the rows and columns in the created array
arr_6

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [81]:
arr_6.reshape(-1,10)

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
arr_6.reshape(-1,2)

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [ ]:
arr_6.reshape(1,-1)

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39]])

In [ ]:
arr_6.shape

(5, 4)

In [85]:
arr_7=arr_6.reshape(2,-1,2)
arr_7

array([[[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [ ]:
arr_6,arr_7

(array([[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]))

In [86]:
arr_7.flatten()          # return 1D array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [ ]:
np.ravel(arr_7)         # return flatten array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

### Stacking

In [92]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = np.array([1, 2, 3,4,5,9])
arr_2 = np.array([6,7,8,9,10,12])


In [90]:
# Horizonal stacking - Appending the elements in the same row
ar_h = np.hstack((arr_1, arr_2))
# display the concatenated array
print(ar_h)


[ 1  2  3  4  5  9  6  7  8  9 10]


In [93]:
# Vertical stacking - Increasing the number of row

ar_v = np.vstack((arr_1, arr_2))
# display the concatenated array
print(ar_v)




[[ 1  2  3  4  5  9]
 [ 6  7  8  9 10 12]]


### Concatenating

In [94]:
import numpy as np

arr1 = np.array([1, 2, 3,6])

arr2 = np.array([4, 5, 6,7])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 6 4 5 6 7]


In [95]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print('arr1')
print(arr1)
print('arr2')
print(arr2)
print('concatenated arr')
print(arr)
print(arr.shape)

arr1
[[1 2]
 [3 4]]
arr2
[[5 6]
 [7 8]]
concatenated arr
[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2))

print('arr1')
print(arr1)
print('arr2')
print(arr2)
print('concatenated arr')
print(arr)
print(arr.shape)

arr1
[[1 2]
 [3 4]]
arr2
[[5 6]
 [7 8]]
concatenated arr
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


## Sort

In [96]:
arr_8=np.array([3,5,4,9,8,7,4,5])

np.sort(arr_8)


array([3, 4, 4, 5, 5, 7, 8, 9])

In [97]:
a = np.array([[4,100],[30,20]])
print(a)
print('-----------')
print(np.sort(a,axis=0)) # sort along the first axis
print('-----------')
print(np.sort(a)) # sort along the last axis

[[  4 100]
 [ 30  20]]
-----------
[[  4  20]
 [ 30 100]]
-----------
[[  4 100]
 [ 20  30]]


In [ ]:
np.random.seed(1)
b=np.random.randint(0, 10, (2,3,3))
print('Array b')
print(b)
print('-----------')
print('sorted array b along axis=0')
print(np.sort(b,axis=0)) # sort along the first axis
print('-----------')
print('sorted array b along axis=1')
print(np.sort(b,axis=1)) # sort along the second axis
print('-----------')
print('sorted array b along last axis')
print(np.sort(b)) # sort along the last axis


Array b
[[[5 8 9]
  [5 0 0]
  [1 7 6]]

 [[9 2 4]
  [5 2 4]
  [2 4 7]]]
-----------
sorted array b along axis=0
[[[5 2 4]
  [5 0 0]
  [1 4 6]]

 [[9 8 9]
  [5 2 4]
  [2 7 7]]]
-----------
sorted array b along axis=1
[[[1 0 0]
  [5 7 6]
  [5 8 9]]

 [[2 2 4]
  [5 2 4]
  [9 4 7]]]
-----------
sorted array b along last axis
[[[5 8 9]
  [0 0 5]
  [1 6 7]]

 [[2 4 9]
  [2 4 5]
  [2 4 7]]]


## Padding


In [101]:
np.set_printoptions(threshold=100)
a = [1, 2, 3, 4, 5]
np.pad(a, (2, 3), 'constant', constant_values=(4, 6))


array([4, 4, 1, 2, 3, 4, 5, 6, 6, 6])

In [ ]:
np.pad(a, (3, 3), 'constant', constant_values=(10,0))

array([10, 10, 10,  1,  2,  3,  4,  5,  0,  0,  0])

In [104]:
a = [[1, 2], [3, 4]]
print(np.array(a))
print('___________________')

print(np.pad(a, ((3, 2), (2, 3)), 'maximum'))

[[1 2]
 [3 4]]
___________________
[[4 4 3 4 4 4 4]
 [4 4 3 4 4 4 4]
 [4 4 3 4 4 4 4]
 [2 2 1 2 2 2 2]
 [4 4 3 4 4 4 4]
 [4 4 3 4 4 4 4]
 [4 4 3 4 4 4 4]]


In [108]:
import sys
np.set_printoptions(threshold=sys.maxsize)
np.pad(a, (5, 5), 'constant')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## Splitting NumPy Arrays

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


If the array has less elements than required, it will adjust from the end accordingly.



In [ ]:
#Split the array in 4 parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


**Split Into Arrays**

The return value of the array_split() method is an array containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:



In [ ]:
#Access the splitted arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


**Splitting 2-D Arrays**

Use the same syntax when splitting 2-D arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.



In [ ]:
#Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
#Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
#Split the 2-D array into three 2-D arrays along rows.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Excercise

Border Rows and Columns
Description
Extract all the border rows and columns from a 2-D array.

Format:
Input: A 2-D Python list
Output: Four NumPy arrays - First column of the input array, first row of the input array, last column of the input array, last row of the input array respectively.

Example:<br>
Input 1:<br>
[[11 12 13 14]<br>
 [21 22 23 24]<br>
 [31 32 33 34]]<br>
Output 1:<br>
[11 21 31]<br>
[11 12 13 14]<br>
[14 24 34]<br>
[31 32 33 34]<br>

In [ ]:
input_list=[[11, 12, 13, 14],
            [21, 22, 23, 24],
            [31, 32, 33, 34]]

In [ ]:
# Convert the input list to a NumPy array
array_2d =np.array(input_list)

In [ ]:
array_2d

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [ ]:
# Extract the first column, first row, last column and last row respectively using
# appropriate indexing
col_first = array_2d[:,0]
row_first = array_2d[0]
col_last = array_2d[:,3]
row_last = array_2d[2]
print(col_first)

print(row_first) 

print(col_last) 

print(row_last)

[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]


# NumPy Cheat Sheets

[Cheat Sheet 1: DataCamp NumPy](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

[Cheat Sheet 2: Basic NumPy](https://cdn.intellipaat.com/mediaFiles/2018/12/Python-NumPy-Cheat-Sheet-.pdf)

[Cheat Sheet 3: A Little Bit of Everything](http://datasciencefree.com/numpy.pdf)

[Cheat Sheet 4: Data Science](https://s3.amazonaws.com/dq-blog-files/numpy-cheat-sheet.pdf)

[Cheat Sheet 5: Scientific Python](https://ipgp.github.io/scientific_python_cheat_sheet/?utm_content=buffer7d821&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer#numpy-import-numpy-as-np)

