# Mathematical operations

addition, subtraction, division, multiplication, etc.
One thing to note here is that NumPy comes with its own set of methods and operations. You should not assume that the operators will work in the same way as lists. Look at the example below.

In [1]:
import numpy as np
# Create 2 lists with elements (1, 2, 3) and (4, 5, 6)
list1 = [1,2,3]
list2 = [4,5,6]

# Use the '+' operator and print the results
list1+list2


[1, 2, 3, 4, 5, 6]

In [ ]:
# Convert the above lists to arrays and use the '+' operator or np.add() for element wise addition

np_1 = np.array([1,2,3])
np_2 = np.array([4,5,6])


print(np_1+np_2)
print()
print(np.add(np_1,np_2))

[5 7 9]

[5 7 9]


In [ ]:
# use the '*' operator or np.multiply() for element wise multiplication
np_1 = np.array([1,2,3])
np_2 = np.array([4,5,6])


print(np_1*np_2)
print()
print(np.multiply(np_1,np_2))

[ 4 10 18]

[ 4 10 18]


In [ ]:
# use the '/' operator or np.divide() for element wise division

print(np_1/np_2)
print()
print(np.divide(np_1,np_2))

[0.25 0.4  0.5 ]

[0.25 0.4  0.5 ]


In [ ]:
# use the '-' operator or np.subtract() for element wise subtraction

print(np_2-np_1)
print()
print(np.subtract(np_2,np_1))

[3 3 3]

[3 3 3]


In [ ]:
# use the '//' operator or np.floor_divide() for element wise floor division
print(np_2//np_1)
print()
print(np.floor_divide(np_2,np_1))


[4 2 2]

[4 2 2]


In [ ]:
# use the '%' operator or np.mod() for element wise modulo
print(np_2%np_1)
print()
print(np.mod(np_2,np_1))

[0 1 0]

[0 1 0]


In [ ]:
# use the '**' operator or np.power() for element wise exponentiation
print(np_2**np_1)
print()
print(np.power(np_2,np_1))

[  4  25 216]

[  4  25 216]


In [ ]:
# Scaler multiplication
np_1 = np.array([1,2,3])*5
np_1

array([ 5, 10, 15])

In [ ]:
# Scaler addition
np_1 = np.array([1,2,3])+5
np_1

array([6, 7, 8])

In [ ]:
# Scaler division
np_1 = np.array([1,2,3])/5
np_1

array([0.2, 0.4, 0.6])

In [ ]:
# # Scaler subtraction
np_1 = np.array([10,20,30])-5
np_1

array([ 5, 15, 25])

In [ ]:
# squaring the terms
print(np.power(np.array([1,2,-1,-2]),2))


[1 4 1 4]


In [ ]:
# np.sin(1.57079633)
print(np.cos(0))



1.0


In [ ]:
# np.log()
print(np.log(10))

2.302585092994046


In [ ]:
# getting the absolute value of the elements
print(np.absolute(np.array([1,2,-1,-2])))

[1 2 1 2]


# Case Study: Cricket Tournament 

A panel wants to select players for an upcoming league match based on their fitness. Players from all significant cricket clubs have participated in a practice match, and their data is collected. Let us now explore NumPy features using the player's data.

#### Height of the payers is stored as a regular Python list: height_in. The height is expressed in inches.

#### Weight of the payers is stored as a regular Python list: weight_lb. The weight is expressed in pounds.

**Multiplication with a factor**

Now, let's convert the height and weight of the players into more generic units. 
* Height in metres
* Weight in kilograms

In [2]:
heights_in = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 72, 75, 74, 74, 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76, 70, 72, 80, 74, 74, 71, 70, 72, 71, 74, 71, 72, 71, 74, 69, 76, 75, 75, 76, 73, 76, 73, 77, 73, 72, 72, 77, 77, 71, 74, 74, 73, 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 76, 73, 74, 75, 75, 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75, 73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72, 72, 74, 73, 74, 76, 75, 80, 72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75, 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 73, 73, 73, 72, 72, 72, 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 74, 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74, 70, 77, 73, 72, 76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72, 75, 75, 70, 72, 70, 74, 71, 76, 73, 76, 71, 69, 72, 72, 69, 73, 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 71, 72, 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76, 73, 73, 73, 75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74, 74, 73, 75, 76, 73, 77, 72, 73, 77, 76, 71, 75, 73, 74, 77, 71, 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 73, 74, 77, 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71, 74, 70, 79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74, 74, 70, 73, 73, 74, 77, 72, 76, 73, 73, 72, 74, 74, 71, 72, 75, 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 79, 76, 73, 76, 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71, 71, 72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75, 79, 72, 77, 73, 75, 75, 75, 73, 73, 76, 77, 75, 70, 71, 71, 75, 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 75, 74, 69, 73, 72, 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70, 75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73, 79, 71, 72, 74, 74, 74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77, 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 72, 71, 71, 71, 72, 72, 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 75, 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70, 75, 71, 76, 73, 68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76, 72, 72, 74, 76, 73, 76, 75, 70, 71, 74, 72, 73, 76, 76, 73, 71, 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 76, 74, 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72, 72, 73, 72, 74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75, 75, 76, 74, 74, 73, 74, 71, 74, 75, 76, 74, 76, 76, 73, 75, 75, 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 71, 82, 72, 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73, 76, 75, 70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72, 77, 74, 75, 75, 75, 75, 72, 74, 71, 76, 71, 75, 76, 83, 75, 74, 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 74, 72, 71, 70, 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75, 77, 76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70, 70, 74, 75, 74, 74, 73, 74, 75, 77, 73, 74, 76, 74, 75, 73, 76, 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 73, 67, 67, 76, 74, 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75, 72, 75, 73, 74, 75, 75, 73]
weights_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 200, 180, 200, 200, 245, 240, 215, 185, 175, 199, 200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 200, 200, 212, 224, 210, 205, 220, 195, 200, 260, 228, 270, 200, 210, 190, 220, 180, 205, 210, 220, 211, 200, 180, 190, 170, 230, 155, 185, 185, 200, 225, 225, 220, 160, 205, 235, 250, 210, 190, 160, 200, 205, 222, 195, 205, 220, 220, 170, 185, 195, 220, 230, 180, 220, 180, 180, 170, 210, 215, 200, 213, 180, 192, 235, 185, 235, 210, 222, 210, 230, 220, 180, 190, 200, 210, 194, 180, 190, 240, 200, 198, 200, 195, 210, 220, 190, 210, 225, 180, 185, 170, 185, 185, 180, 178, 175, 200, 204, 211, 190, 210, 190, 190, 185, 290, 175, 185, 200, 220, 170, 220, 190, 220, 205, 200, 250, 225, 215, 210, 215, 195, 200, 194, 220, 180, 180, 170, 195, 180, 170, 206, 205, 200, 225, 201, 225, 233, 180, 225, 180, 220, 180, 237, 215, 190, 235, 190, 180, 165, 195, 200, 190, 190, 185, 185, 205, 190, 205, 206, 220, 208, 170, 195, 210, 190, 211, 230, 170, 185, 185, 241, 225, 210, 175, 230, 200, 215, 198, 226, 278, 215, 230, 240, 184, 219, 170, 218, 190, 225, 220, 176, 190, 197, 204, 167, 180, 195, 220, 215, 185, 190, 205, 205, 200, 210, 215, 200, 205, 211, 190, 208, 200, 210, 232, 230, 210, 220, 210, 202, 212, 225, 170, 190, 200, 237, 220, 170, 193, 190, 150, 220, 200, 190, 185, 185, 200, 172, 220, 225, 190, 195, 219, 190, 197, 200, 195, 210, 177, 220, 235, 180, 195, 195, 190, 230, 190, 200, 190, 190, 200, 200, 184, 200, 180, 219, 187, 200, 220, 205, 190, 170, 160, 215, 175, 205, 200, 214, 200, 190, 180, 205, 220, 190, 215, 235, 191, 200, 181, 200, 210, 240, 185, 165, 190, 185, 175, 155, 210, 170, 175, 220, 210, 205, 200, 205, 195, 240, 150, 200, 215, 202, 200, 190, 205, 190, 160, 215, 185, 200, 190, 210, 185, 220, 190, 202, 205, 220, 175, 160, 190, 200, 229, 206, 220, 180, 195, 175, 188, 230, 190, 200, 190, 219, 235, 180, 180, 180, 200, 234, 185, 220, 223, 200, 210, 200, 210, 190, 177, 227, 180, 195, 199, 175, 185, 240, 210, 180, 194, 225, 180, 205, 193, 230, 230, 220, 200, 249, 190, 208, 245, 250, 160, 192, 220, 170, 197, 155, 190, 200, 220, 210, 228, 190, 160, 184, 180, 180, 200, 176, 160, 222, 211, 195, 200, 175, 206, 240, 185, 260, 185, 221, 205, 200, 170, 201, 205, 185, 205, 245, 220, 210, 220, 185, 175, 170, 180, 200, 210, 175, 220, 206, 180, 210, 195, 200, 200, 164, 180, 220, 195, 205, 170, 240, 210, 195, 200, 205, 192, 190, 170, 240, 200, 205, 175, 250, 220, 224, 210, 195, 180, 245, 175, 180, 215, 175, 180, 195, 230, 230, 205, 215, 195, 180, 205, 180, 190, 180, 190, 190, 220, 210, 255, 190, 230, 200, 205, 210, 225, 215, 220, 205, 200, 220, 197, 225, 187, 245, 185, 185, 175, 200, 180, 188, 225, 200, 210, 245, 213, 231, 165, 228, 210, 250, 191, 190, 200, 215, 254, 232, 180, 215, 220, 180, 200, 170, 195, 210, 200, 220, 165, 180, 200, 200, 170, 224, 220, 180, 198, 240, 239, 185, 210, 220, 200, 195, 220, 230, 170, 220, 230, 165, 205, 192, 210, 205, 200, 210, 185, 195, 202, 205, 195, 180, 200, 185, 240, 185, 220, 205, 205, 180, 201, 190, 208, 240, 180, 230, 195, 215, 190, 195, 215, 215, 220, 220, 230, 195, 190, 195, 209, 204, 170, 185, 205, 175, 210, 190, 180, 180, 160, 235, 200, 210, 180, 190, 197, 203, 205, 170, 200, 250, 200, 220, 200, 190, 170, 190, 220, 215, 206, 215, 185, 235, 188, 230, 195, 168, 190, 160, 200, 200, 189, 180, 190, 200, 220, 187, 240, 190, 180, 185, 210, 220, 219, 190, 193, 175, 180, 215, 210, 200, 190, 185, 220, 170, 195, 205, 195, 210, 190, 190, 180, 220, 190, 186, 185, 190, 180, 190, 170, 210, 240, 220, 180, 210, 210, 195, 160, 180, 205, 200, 185, 245, 190, 210, 200, 200, 222, 215, 240, 170, 220, 156, 190, 202, 221, 200, 190, 210, 190, 200, 165, 190, 185, 230, 208, 209, 175, 180, 200, 205, 200, 250, 210, 230, 244, 202, 240, 200, 215, 177, 210, 170, 215, 217, 198, 200, 220, 170, 200, 230, 231, 183, 192, 167, 190, 180, 180, 215, 160, 205, 223, 175, 170, 190, 240, 175, 230, 223, 196, 167, 195, 190, 250, 190, 190, 190, 170, 160, 150, 225, 220, 209, 210, 176, 260, 195, 190, 184, 180, 195, 195, 219, 225, 212, 202, 185, 200, 209, 200, 195, 228, 210, 190, 212, 190, 218, 220, 190, 235, 210, 200, 188, 210, 235, 188, 215, 216, 220, 180, 185, 200, 210, 220, 185, 231, 210, 195, 200, 205, 200, 190, 250, 185, 180, 170, 180, 208, 235, 215, 244, 220, 185, 230, 190, 200, 180, 190, 196, 180, 230, 224, 160, 178, 205, 185, 210, 180, 190, 200, 257, 190, 220, 165, 205, 200, 208, 185, 215, 170, 235, 210, 170, 180, 170, 190, 150, 230, 203, 260, 246, 186, 210, 198, 210, 215, 180, 200, 245, 200, 192, 192, 200, 192, 205, 190, 186, 170, 197, 219, 200, 220, 207, 225, 207, 212, 225, 170, 190, 210, 230, 210, 200, 238, 234, 222, 200, 190, 170, 220, 223, 210, 215, 196, 175, 175, 189, 205, 210, 180, 180, 197, 220, 228, 190, 204, 165, 216, 220, 208, 210, 215, 195, 200, 215, 229, 240, 207, 205, 208, 185, 190, 170, 208, 225, 190, 225, 185, 180, 165, 240, 220, 212, 163, 215, 175, 205, 210, 205, 208, 215, 180, 200, 230, 211, 230, 190, 220, 180, 205, 190, 180, 205, 190, 195]

In [3]:
len(heights_in),len(weights_lb)

(1015, 1015)

In [4]:
# Importing the numpy library 

import numpy as np

In [5]:
# Convert the lists into NumPy arrays
heights_in=np.array(heights_in)
weights_lb=np.array(weights_lb)

In [6]:
# Print the type of the created arrays
type(weights_lb)

numpy.ndarray

In [7]:
# Print the length of the created arrays

weights_lb.size

1015

In [8]:
# Convert the units of height and weight using appropriate factors (look in the video for the factors)

heights_m = heights_in * 0.0254           # 1 inch = 0.025 meters        1 inch = 2.54 cm
weights_kg = weights_lb * 0.45            # 1 lb = 0.45 Kgs

In [10]:
# Print the newly created arrays

import sys

np.set_printoptions(threshold=sys.maxsize)
print(heights_m)
print(weights_kg)

[1.8796 1.8796 1.8288 1.8288 1.8542 1.7526 1.7526 1.8034 1.9304 1.8034
 1.8542 1.8542 1.8796 1.8796 1.7526 1.778  1.8542 1.905  1.9812 2.0066
 1.9304 1.8796 1.9304 1.8288 1.8034 1.905  1.9558 1.8796 1.8542 1.8796
 1.9812 1.8542 1.905  1.8542 1.905  1.905  1.8796 1.7526 1.8034 1.8796
 1.8542 1.8542 1.9304 1.8796 1.8796 1.778  1.8288 1.9558 1.8796 1.778
 1.8542 1.905  1.9304 1.9304 1.9812 1.8796 1.8796 1.9304 1.9558 2.0574
 1.9812 1.905  1.9558 1.905  1.9304 1.8796 1.8288 1.8288 1.905  1.8542
 1.8542 1.8542 1.778  1.778  1.778  1.9304 1.7272 1.8034 1.8288 1.905
 1.905  1.905  1.905  1.7272 1.8796 1.9812 1.8034 1.8542 1.9304 1.8796
 1.8796 2.0066 1.905  1.8542 1.9304 1.8796 1.8796 1.8542 1.8288 1.8796
 1.8542 1.8796 1.8288 1.8542 1.7526 1.8288 1.8542 1.905  1.905  1.8542
 1.8288 1.8288 1.9304 1.8796 1.8288 1.9558 1.8796 1.9558 1.905  1.9304
 2.032  1.8796 1.8796 1.905  1.9812 1.8542 1.8542 1.8796 1.905  1.9304
 1.8034 1.8542 1.8796 1.9304 1.9304 1.8796 1.8542 1.8796 1.778  1.8288
 1.8542 

**Deriving new data from existing**

Now, let us try to calculate the Body Mass Index (BMI) value for the players. The formula for BMI is:

$$ BMI = \frac{Weight\ of\ the\ individual}{(Height\ of\ the\ individual) ^ 2} $$

In [11]:
# Calculate the bmi value based on the formula above

bmi = weights_kg/(heights_m**2)

In [12]:
# Check the newly created array 'bmi'

bmi

array([22.92736507, 27.38546383, 28.25526484, 28.25526484, 24.60691729,
       25.78455062, 30.61915387, 27.67313608, 27.89522546, 24.90582248,
       24.60691729, 23.55981443, 23.56423632, 20.37988006, 26.37056314,
       26.33423634, 24.73780515, 22.94004588, 25.10729874, 25.70506663,
       24.75550311, 29.29607758, 23.54791759, 24.21879844, 26.56621064,
       27.9000558 , 23.88139369, 24.83797882, 23.82159015, 23.94635907,
       22.92903994, 23.55981443, 24.8000496 , 26.17757159, 30.38006076,
       29.76005952, 27.38546383, 27.10307878, 24.21399407, 25.34747582,
       26.17757159, 28.14088946, 24.15171035, 26.11172132, 26.23909558,
       26.47658357, 25.29518948, 25.88131336, 26.74859258, 27.75770858,
       26.17757159, 24.8000496 , 25.60081297, 27.0499156 , 24.07549194,
       26.11172132, 28.02233508, 23.54791759, 23.52846669, 27.64065885,
       26.13910553, 33.48006696, 23.52846669, 26.04005208, 22.94412484,
       28.02233508, 24.21879844, 27.58252044, 26.04005208, 28.79

**Indexing through arrays**

For **one-dimensional arrays**, indexing is **similar to Python lists** - indexing starts at 0.

In [13]:
# Obtain the 5th element from the array 'bmi'

bmi[4]

24.606917294149852

In [ ]:
# Obtain the 2nd last element from the array 'bmi'

bmi[-2]

23.56004712009424

In [ ]:
# Obtain the first five elements from the array 'bmi'

bmi[:5]

array([22.92736507, 27.38546383, 28.25526484, 28.25526484, 24.60691729])

In [ ]:
# Obtain the last three elements from the array 'bmi'
bmi[-3:]

array([25.42005084, 23.56004712, 25.5231323 ])

As you can see, the NumPy way is clearly more concise. Even simple mathematical operations on lists required loops, unlike with arrays.

## Subsets

In [14]:
# Check for the elements where bmi value is less than 21

bmi<21

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [15]:
# Filter the elements where bmi value is less than 21
bmi[bmi<21]


array([20.37988006, 20.37988006, 20.5289538 , 20.5289538 , 20.18233203,
       20.94205727, 20.18233203, 20.94205727, 20.94205727, 20.5289538 ,
       19.99919669, 19.34403869, 20.5289538 , 20.75485206])

In [16]:
# Count the number of elements where bmi value is less than 21

bmi[bmi<21].size

14

#  Statistical Analysis

Statistical analysis includes finding minimum (`.min()`), maximum (`max()`), mean(`.mean()`), median(`.median()`), mode, correlation, covariance(`.cov()`), standard deviation (`.std()`) and variance (`.var()`) of the numpy array.



In [17]:
bmi[bmi<21].max()

20.942057271616893

In [ ]:
# Find the maximum bmi values among the players

bmi.max()

34.9827088543066

In [ ]:
# Find the minimum bmi values among the players

bmi.min()

19.344038688077376

In [18]:
np.min(bmi)

19.344038688077376

In [ ]:
# Find the average bmi among the players

bmi.mean()

25.85050120927726

In [20]:
np.median(bmi)

25.84233007801196

In [21]:
np.mode(bmi)

AttributeError: ignored

In [22]:
! pip install statistics

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for statistics: filename=statistics-1.0.3.5-py3-none-any.whl size=7453 sha256=924d37f3372632afd686659bf7b5a0bb4301086acf7a7219eebf14a4d571ef2f
  Stored in directory: /root/.cache/pip/wheels/26/3c/70/9467407f3aa90862061eadcd286627b23a8bab6789b667776f
Successfully built statistics


In [23]:
# to find mode in numpy array
# Note: This step works fine in Jupyter Notebbok
import statistics as st
st.mode(bmi)

26.177571589521115

In [24]:
# to find multiple mode in numpy array
# Note: This step works fine in Jupyter Notebbok
st.multimode(bmi)

[26.177571589521115, 25.47485007314792]

In [25]:
st.mode(bmi)

26.177571589521115

In [27]:
# # If above code does't work try this in the Google Colab
# mymode = lambda x : x[0][x[1].argmax()]
# mymode(np.unique(bmi))

In [ ]:
#Find the standard deviation of the bmi
bmi.std()

2.26658142199571

In [ ]:
#Find the variance of the bmi
np.var(bmi)

5.137391342536095

In [ ]:
#Find the covariance of the bmi
np.cov(bmi)

array(5.1424578)

In [ ]:
#Find the correlation of the bmi
np.corrcoef(bmi)

1.0

In [ ]:
# Percentile of the array
import numpy as np

# 2D array
arr = [[14, 17, 12, 33, 44],
       [15, 6, 27, 8, 19],
       [23, 2, 54, 1, 4,]]

print("\narr : \n", arr)
# Percentile of the flattened array
print("\n50th Percentile of arr, axis = None : ",np.percentile(arr, 50))
print("0th Percentile of arr, axis = None : ",np.percentile(arr, 0))

# Percentile along the axis = 0
print("\n50th Percentile of arr, axis = 0 : ",np.percentile(arr, 50, axis =0))
print("0th Percentile of arr, axis = 0 : ",np.percentile(arr, 0, axis =0))


arr : 
 [[14, 17, 12, 33, 44], [15, 6, 27, 8, 19], [23, 2, 54, 1, 4]]

50th Percentile of arr, axis = None :  15.0
0th Percentile of arr, axis = None :  1.0

50th Percentile of arr, axis = 0 :  [15.  6. 27.  8. 19.]
0th Percentile of arr, axis = 0 :  [14.  2. 12.  1.  4.]


In [ ]:
# Quantile of the array
import numpy as np

# 2D array
arr = [[14, 17, 12, 33, 44],
       [15, 6, 27, 8, 19],
       [23, 2, 54, 1, 4,]]

print("\narr : \n", arr)
# Percentile of the flattened array
print("\n50th Quantile of arr, axis = None : ",np.quantile(arr, 0.50))
print("0th Quantile of arr, axis = None : ",np.quantile(arr, 0))

# Percentile along the axis = 0
print("\n50th Quantile of arr, axis = 0 : ",np.quantile(arr, 0.50, axis =0))
print("0th Quantile of arr, axis = 0 : ",np.quantile(arr, 0, axis =0))


arr : 
 [[14, 17, 12, 33, 44], [15, 6, 27, 8, 19], [23, 2, 54, 1, 4]]

50th Quantile of arr, axis = None :  15.0
0th Quantile of arr, axis = None :  1

50th Quantile of arr, axis = 0 :  [15.  6. 27.  8. 19.]
0th Quantile of arr, axis = 0 :  [14  2 12  1  4]


# Aggregation of array elements

In [ ]:
# Reducing the elements to a single value based on addition
x=np.array([1,2,3,4,70,6])
print(np.add.reduce(x))

print(x.sum())

86
86


In [ ]:
# Reducing the elements to a single value based on addition
y=np.array([[1,2,3,4,70,6],[1,2,3,4,70,6]])
print(np.add.reduce(y))

print(y.sum())

[  2   4   6   8 140  12]
172


In [ ]:
# Cummulative addition of elements at each element
print(np.add.accumulate(x))

[ 1  3  6 10 80 86]


In [ ]:
# Cummulative addition of elements at each element
print(np.add.accumulate(y))

[[  1   2   3   4  70   6]
 [  2   4   6   8 140  12]]


In [ ]:
print(np.cumsum(x))

[ 1  3  6 10 80 86]


In [ ]:
print(np.cumsum(y))

[  1   3   6  10  80  86  87  89  92  96 166 172]


# Practice Exercise 1

You are provided with 2 lists that contain the data of an ecommerce website. The first list contains the data for the number of items sold for a particular product and the second list contains the price of the product sold. As a part of this exercise, solve the questions that are provided below.

In [32]:
number = [8, 9, 9, 1, 6, 9, 5, 7, 3, 9, 7, 3, 4, 8, 3, 5, 8, 4, 8, 7, 5, 7, 3, 6, 1, 2, 7, 4, 7, 7, 8, 4, 3, 4, 2, 2, 2, 7, 3, 5, 6, 1, 1, 3, 2, 1, 1, 7, 7, 1, 4, 4, 5, 6, 1, 2, 7, 4, 5, 8, 1, 4, 8, 6, 2, 4, 3, 7, 3, 6, 2, 3, 3, 3, 2, 4, 6, 8, 9, 3, 9, 3, 1, 8, 6, 6, 3, 3, 9, 4, 6, 4, 9, 6, 7, 1, 2, 8, 7, 8, 1, 4]
price = [195, 225, 150, 150, 90, 60, 75, 255, 270, 225, 135, 195, 30, 15, 210, 105, 15, 30, 180, 60, 165, 60, 45, 225, 180, 90, 30, 210, 150, 15, 270, 60, 210, 180, 60, 225, 150, 150, 120, 195, 75, 240, 60, 45, 30, 180, 240, 285, 135, 165, 180, 240, 60, 105, 165, 240, 120, 45, 120, 165, 285, 225, 90, 105, 225, 45, 45, 45, 75, 180, 90, 240, 30, 30, 60, 135, 180, 15, 255, 180, 270, 135, 105, 135, 210, 180, 135, 195, 225, 75, 225, 15, 240, 60, 15, 180, 255, 90, 15, 150, 230, 150]

**How many different products are sold by the company in total?**

-  99
-  100
-  101
-  102


In [33]:
# Type your code here
import numpy as np
number=np.array(number)

number.size

102

**How many items were sold in total?**

-  460
-  490
-  500
-  520


In [ ]:
# Type your code here
number.sum()

490

**What is the average price of the products sold by the ecommerce company?**

-  139
-  151
-  142
-  128

In [34]:
# Type your code here

price=np.array(price)

price.mean()

139.01960784313727

**What is the price of the costliest item sold?**

-  225
-  310
-  280
-  285

In [ ]:
# Type your code here
price.max()

285

**What is the total revenue of the company? [Revenue = Price\*Quantity]**

-  67100
-  53900
-  45300
-  71200

In [ ]:
# Type your code here

Revenue= (price*number).sum()
# Revenue=Revenue.sum()
Revenue

67100

**Demand for the 20th product in the list is more than the 50th product. [True/False]**
-  True
-  False
-  Can't be calculated

In [30]:
# Type your code here
number[19]>number[49]

True

In [31]:
number[19]

7

In [ ]:
number[49]

1

**How many products fall under the category of expensive goods? 
An expensive good is that good whose price is more than the average price of the products sold by the company.**

-  48
-  50
-  52
-  54

In [43]:
# Type your code here

price[price>price.mean()].size

52

In [39]:
price[price>price.mean()].size

52

# Linear Algebra

    7x + 5y - 3z = 16
    3x - 5y + 2z = -8
    5x + 3y - 7z = 0

In [44]:
import numpy as np

In [45]:
# to get the solution of the equation use np.linalg.solve()

a = np.array([ [7,5,-3],[3,-5,2],[5,3,-7] ])
b = np.array([16,-8,0])

np.linalg.solve(a,b)

array([1., 3., 2.])

In [46]:
a=np.array([[3,2,-2],[3,3,-3],[-2,4,-5]])
b=np.array([1,-3,-1])
np.linalg.solve(a,b)

array([  3., -25., -21.])

<img src='https://media.nagwa.com/763142684617/en/thumbnail_l.jpeg'>

In [ ]:
# to get the inverse of the matrix use np.linalg.inv()
a = np.array([ [7,5,-3],[3,-5,2],[5,3,-7] ])
print(a)

np.linalg.inv(a)

[[ 7  5 -3]
 [ 3 -5  2]
 [ 5  3 -7]]


array([[ 0.11328125,  0.1015625 , -0.01953125],
       [ 0.12109375, -0.1328125 , -0.08984375],
       [ 0.1328125 ,  0.015625  , -0.1953125 ]])

<img src='https://cdn1.byjus.com/wp-content/uploads/2018/04/inverse-matrix-4.jpg'>

In [47]:
np.linalg.inv(np.array([[2,1],[7,4]]))

array([[ 4., -1.],
       [-7.,  2.]])

In [ ]:
np.round(np.linalg.inv(a),2)

array([[ 0.11,  0.1 , -0.02],
       [ 0.12, -0.13, -0.09],
       [ 0.13,  0.02, -0.2 ]])

In [ ]:
# to get the determinant of the matrix use np.linalg.det()
a = np.array([ [7,5,-3],[3,-5,2],[5,3,-7] ])
print(a)

np.linalg.det(a)

[[ 7  5 -3]
 [ 3 -5  2]
 [ 5  3 -7]]


255.99999999999994

In [ ]:
np.round(np.linalg.det(a),2)

256.0

In [ ]:
A = np.array([[1, 1],
              [0, 1]])

B = np.array([[2, 0],
              [3, 4]])

In [ ]:
A * B     # elementwise product

array([[2, 0],
       [0, 4]])

In [ ]:
A @ B     # matrix product or dot product

array([[5, 4],
       [3, 4]])

In [ ]:
A.dot(B)  # another matrix product

array([[5, 4],
       [3, 4]])

In [49]:
v = np.array([4, 9, 12])
s = np.array([21, 32, 44])
r = np.cross(v, s)       # cros product
print(r)

[ 12  76 -61]


# Creating Special NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

The following ways are commonly used:
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.linspace()```: Create array of fixed length
-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
* ```np.random.random()```: Create array of random numbers between 0 and 1
-  `np.random.randint()`: Create a random array of integers within a particular range

In [ ]:
# importing the NumPy library

import numpy as np

In [ ]:
# creating an array with 4 elements and increments of a fixed step size
# default step size is one
np_1 = np.arange(4)
np_1

array([0, 1, 2, 3])

In [51]:
# creating an array between 2 and 11 elements and increments of a fixed step size 2
# default step size is one
np_1 = np.arange(2,11,2)
print(np_1)

[ 2  4  6  8 10]


In [ ]:
# creating an array of zeroes with 5 elements
np_2 = np.zeros(5)
print(np_2)

[0. 0. 0. 0. 0.]


In [ ]:
# data type of np_2
np_2.dtype

# Default data type will be float

dtype('float64')

In [53]:
# specifying the data type of the array in the provided attribute

np_2 = np.zeros(5,dtype="int")
np_2

array([0, 0, 0, 0, 0])

In [ ]:
np_2

array([0, 0, 0, 0, 0])

In [ ]:
# adding the two arrays: np_1 and np_2
print(np_1 + np_2)

[ 2  4  6  8 10]


In [ ]:
# check the dimension of the arrays
# array np_1
np_1.size

5

In [ ]:
# check the dimension of the arrays
# array np_2
np_2.size

5

In [ ]:
# creating a third array with all the 5 elements as ones

np_3 = np.ones(5)
print(np_3)

[1. 1. 1. 1. 1.]


In [ ]:
# check the dimension of the arrays
np_3.size

5

In [ ]:
# creating a third array with all the 5 elements as ones

np_4 = np.ones(5,dtype=int)

# checking the created array:np_3
print(np_4)

[1 1 1 1 1]


In [ ]:
# subtracting the array np_3 from array np_2

print(np_2 - np_3)

[-1. -1. -1. -1. -1.]


 **np.linespace()**
 
![](https://i.imgur.com/SbJ7owv.jpg)

In [ ]:
# creating an array of fixed length
np_5 = np.linspace(1,90,9)

# checking the created array:np_4
print(np_5)

[ 1.    12.125 23.25  34.375 45.5   56.625 67.75  78.875 90.   ]


In [ ]:
# creating an array of fixed length
np_6 = np.linspace(1,10,10)

# checking the created array:np_4
print(np_6)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
np_7=np.linspace(1,90,9,retstep=True)
print(np_7)

(array([ 1.   , 12.125, 23.25 , 34.375, 45.5  , 56.625, 67.75 , 78.875,
       90.   ]), 11.125)


In [63]:
# Empty array: Return a new array of given shape and type, without initializing entries.
x = np.arange(1, 8)
print(x)

[1 2 3 4 5 6 7]


In [62]:
# Creating empty arrays
y = np.empty(7)
print(y)

[2.92965197e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 3.16202013e-322]


In [64]:
# filling the empty array
np.multiply(x,10,y)

array([10., 20., 30., 40., 50., 60., 70.])

In [65]:
print(y)

[10. 20. 30. 40. 50. 60. 70.]


In [ ]:
# printing the output obtained above
y*x

array([ 10.,  40.,  90., 160., 250., 360.])

In [68]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is 'int' only
np.full((2,4,3), 8.3)

array([[[8.3, 8.3, 8.3],
        [8.3, 8.3, 8.3],
        [8.3, 8.3, 8.3],
        [8.3, 8.3, 8.3]],

       [[8.3, 8.3, 8.3],
        [8.3, 8.3, 8.3],
        [8.3, 8.3, 8.3],
        [8.3, 8.3, 8.3]]])

In [ ]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type her is int only
arr = [0, 1, 2]
np.tile(arr, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [ ]:
# You can also create multidimensional arrays using np.tile()
np.tile(arr, (3,2))   # can't do columnwise

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [ ]:
np.tile(arr, (2,4,3))

array([[[0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2]]])

In [70]:
# Create a 3 x 3 identity matrix using np.eye()
# The default data type here is float. So if we want integer values, we need to specify the dtype to be int
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.eye(6, dtype = int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [73]:
# Create a 3 x 3 array of random numbers between 0 and 1
np.random.random([2,3])

array([[0.99651513, 0.53678011, 0.24110866],
       [0.55728588, 0.90558899, 0.61682071]])

**.randint()**

`random.randint(low, high=None, size=None, dtype=int)`

Return random integers from low (inclusive) to high (exclusive).

In [79]:
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(20, 30, (4,4))

array([[22, 26, 21, 20],
       [21, 25, 23, 23],
       [28, 28, 29, 23],
       [27, 23, 27, 21]])

In [ ]:
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(0, 10, (4,4))

array([[0, 2, 3, 3],
       [6, 1, 3, 3],
       [2, 5, 0, 8],
       [5, 6, 8, 0]])

**random.seed()**

Seed function is used to save the state of a random function, so that it can generate same random numbers on multiple executions of the code on the same machine or on different machines (for a specific seed value). The seed value is the previous value number generated by the generator. For the first time when there is no previous value, it uses current system time. 

In [85]:
np.random.seed(0)
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(20, 30, (4,4))

array([[25, 20, 23, 23],
       [27, 29, 23, 25],
       [22, 24, 27, 26],
       [28, 28, 21, 26]])

In [ ]:
np.random.seed(1)
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(0, 10, (4,4))

array([[5, 8, 9, 5],
       [0, 0, 1, 7],
       [6, 9, 2, 4],
       [5, 2, 4, 2]])

# NumPy Array - Search

## Searching Arrays

### You can search an array for a certain value, and return the indexes that get a match.

### To search an array, use the where() method.

In [86]:
import numpy as np

#Find the indexes where the value is 4:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [ ]:
arr[x]

array([4, 4, 4])

In [87]:
#Find the indexes where the values are even:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)


(array([1, 3, 5, 7]),)


In [ ]:
arr[x]

array([2, 4, 6, 8])

In [ ]:
#Find the indexes where the values are odd:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


In [ ]:
arr[x]

array([1, 3, 5, 7])

In [92]:
#Find the indexes where the value 7 should be inserted:

arr = np.array([10,6, 7, 8,5, 9,7])

x = np.searchsorted(arr, 10)

print(x)

[6,7,7,8,9,10]

7


[6, 7, 7, 8, 9, 10]

# NumPy Cheat Sheets

[Cheat Sheet 1: DataCamp NumPy](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

[Cheat Sheet 2: Basic NumPy](https://cdn.intellipaat.com/mediaFiles/2018/12/Python-NumPy-Cheat-Sheet-.pdf)

[Cheat Sheet 3: A Little Bit of Everything](http://datasciencefree.com/numpy.pdf)

[Cheat Sheet 4: Data Science](https://s3.amazonaws.com/dq-blog-files/numpy-cheat-sheet.pdf)

[Cheat Sheet 5: Scientific Python](https://ipgp.github.io/scientific_python_cheat_sheet/?utm_content=buffer7d821&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer#numpy-import-numpy-as-np)

